<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Partner</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_id" class="easyui-textbox" mapping="partner_id" uppercase="true" maxlength="14" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_name" class="easyui-textbox" mapping="partner_name" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Name harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Address</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_addressline1" class="easyui-textbox" mapping="partner_addressline1" uppercase="true" maxlength="100" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Alamat harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">..</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_addressline2" class="easyui-textbox" mapping="partner_addressline2" uppercase="true" maxlength="100" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">..</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_postcode" class="easyui-textbox" mapping="partner_postcode" uppercase="true" maxlength="10" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_city" class="easyui-textbox" mapping="partner_city" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'City harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Country</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partner_country" class="easyui-combo" style="width: 400px" mapping="partner_country" display="country_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Country harus diisi'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Phone</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_phone" class="easyui-textbox" mapping="partner_phone" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Phone harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">HP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_mobilephone" class="easyui-textbox" mapping="partner_mobilephone" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_email" class="easyui-textbox" mapping="partner_email" uppercase="true" maxlength="150" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_partner_isdisabled" class="easyui-checkbox c1" mapping="partner_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnertype_id" class="easyui-combo" style="width: 400px" mapping="partnertype_id" display="partnertype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Type harus diisi'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Org</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnerorg_id" class="easyui-combo" style="width: 400px" mapping="partnerorg_id" display="partnerorg_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Org harus diisi'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editbankgrid')">Bank</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editcontactgrid')">Contact</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

