<div id="pnl_editbankgrid">
	<div class="fgta-page-title">Daftar Bank</div>
	<div id="pnl_editbankgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editbankgrid-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th type="check">chk</th>
					<th mapping="partnerbank_id">partnerbank_id</th>
					<th mapping="partnerbank_accnum">partnerbank_accnum</th>
					<th mapping="partnerbank_accname">partnerbank_accname</th>
					<th mapping="partnerbank_isdisabled">partnerbank_isdisabled</th>
					<th mapping="bank_name">bank_name</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 5px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Account Number</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Account Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Disabled</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Bank</td>

				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_editbankgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editbankgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editbankgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
