<div id="pnl_editcontactgrid">
	<div class="fgta-page-title">Daftar Contact</div>
	<div id="pnl_editcontactgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editcontactgrid-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th type="check">chk</th>
					<th mapping="partnercontact_id">partnercontact_id</th>
					<th mapping="partnercontact_name">partnercontact_name</th>
					<th mapping="partnercontact_position">partnercontact_position</th>
					<th mapping="partnercontact_mobilephone">partnercontact_mobilephone</th>
					<th mapping="partnercontact_email">partnercontact_email</th>
					<th mapping="partnecontact_isdisabled">partnecontact_isdisabled</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 5px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Position</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">HP</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Email</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Disabled</td>

				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_editcontactgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editcontactgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editcontactgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
